### ISSUE TITLE
Add historic ISO-4217 currencies

### ISSUE THREAD

**Issue by remyvd** [remyvd/NodaMoney#30]
Add all the [historic currencies codes](http://en.wikipedia.org/wiki/ISO_4217#Historical_currency_codes) and make sure they are marked with IsObsolete = true.

Best way, I think, is to have a 'ISO-421 HISTORIC' namespace.

**Comment by JayT82** [comment]
In this issue, some discussion or thought sharing might be useful. The library could have the historic values "Hard coded". Or another datasource could  be used, on that uses namespaces  for differentiation.
