### ISSUE TITLE
Concurrency dependency and compatability

### ISSUE THREAD

**Issue by smattox** [remyvd/NodaMoney#35]
This may or may not qualify as an issue for the library as a whole.

The 0.5.0.0 release of NodaMoney on NuGet adds a project dependency upon System.Collections.Concurrent, for the purpose of two ConcurrentDictionaries in the CurrencyRegistry. System.Collections.Concurrent does not appear to be broadly compatible with all PCL profiles, or at least the one that we're dependent upon (78), and so we're unable to use this version. Given the apparently very limited application of System.Collections.Concurrent classes, I wanted to at least float the possibility of removing the dependency in future releases (would locks suffice?).

I know I probably should just utilize a private fork and address this issue on my own, but my organization won't be supporting VS2015/C#6 for a while yet, which means needing to base off months old code before the conversion, and just generally putting up with a whole bunch of maintenance and maintainability headaches. :)

Thanks for reading; great library! I dearly want to make use of it. :)

**Comment by remyvd** [comment]
Thanks for the comment!

You normally would change currencies only on the startup of an application, so the Concurrent Dictionary is probably overkill for the CurrencyRegistry.

The focus is to have as less as possible dependencies, so I will check the compatibility with the profiles and improve this in the next version.

**Comment by remyvd** [comment]
The dependency to System.Collections.Concurrent has been removed (replaced by locks), so you should be able to use the next version again.
