### ISSUE TITLE
CSD currency code exception

### ISSUE THREAD

**Issue by DejanMilicic** [remyvd/NodaMoney#37]
According to https://en.wikipedia.org/wiki/ISO_4217 CSD (Serbian Dinar) is valid currency code. However, when attempting to instantiate Money object with that currency code, exception is thrown

CSD is an unknown ISO-4217 currency code!

**Comment by remyvd** [comment]
CSD is a historic currency that is replaced in 2006 by RSD (Serbian Dinar).

Historic currencies will be added in the future (see #30). Some are already added and I will add CSD asap, so that you can use it.
