### ISSUE TITLE
Nuget package deploy - readme and license

### ISSUE THREAD

**Issue by DejanMilicic** [remyvd/NodaMoney#38]
Nuget package deploys Radme and License files into the root directory of the project. This is a bit unusually. Usual practice is to ask for licence acceptance and to open readme upon installation, but location of readme points to packages/package.
Can something be done regarding this?

**Comment by remyvd** [comment]
Didn't realize that these files were deployed into the project root. Thanks for pointing this out! Will fix it.

**Comment by DejanMilicic** [comment]
@remyvd Thanx, could you do the same for other nuget package (https://www.nuget.org/packages/NodaMoney.Serialization.AspNet/) as well?

**Comment by remyvd** [comment]
It is fixed in both and will be in version 0.6.0 (released soon).
