### ISSUE TITLE
Nuget package update fails for NodaMoney.Serialization.AspNet to 0.6.0 for target NF4.5.2

### ISSUE THREAD

**Issue by v0id24** [remyvd/NodaMoney#42]
Nuget package updater throws error when trying to update package from 0.5.0 to 0.6.0 .

> Could not install package 'NodaMoney.Serialization.AspNet 0.6.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by remyvd** [comment]
Sorry for this, upgraded to the target framework to v4.6, without thinking about other previous targets. Will add more targets, so that is compatible.
