### ISSUE TITLE
Add support for .NETStandard

### ISSUE THREAD

**Issue by StevenLiekens** [remyvd/NodaMoney#44]
Please create and publish packages for the .NET Platform Standard (netstandard1.0).

**Comment by remyvd** [comment]
Will do that.

**Comment by StevenLiekens** [comment]
Are you using VS 2015 with Update 3? There should already be an option to convert the project to netstandard1.x in the project settings.

**Comment by remyvd** [comment]
Yes, I'm running Update 3. Must of the code is already changed to NET core (dotnet branch) and packages seems to work for netstandard1.0, but there are a couple of minor things still to do (build script, versioning, etc.).
