### ISSUE TITLE
Plus operator

### ISSUE THREAD

**Issue by DejanMilicic** [remyvd/NodaMoney#49]
If I try something like this

Money money  = new Money(10, "GBP");
list[gbpAnountNdx] += 10;

I do not end up with 20 GBP, I end up with the exception.
Reson? My local culture is USA, so plus operator first created sctruct Money using "USD" and then tried to perform addition, which caused exception since I attempted to add two different currencies.

Can we introduce addition operator override that would treat numbers in a proper way - look at currency, create new Money with that currency and then call existing override that sums up two Money structs?

**Comment by remyvd** [comment]
Sounds like a good proposal. A user is probably expecting that the same currency in this case, so optimize for would be nice.
