### ISSUE TITLE
Newtonsoft Json serialization of default(Money) fails

### ISSUE THREAD

**Issue by ptjhuang** [remyvd/NodaMoney#66]
default(Money) fails serialization round-trip of MoneyJsonConverter.  Should that be fixed?  

```
[Fact]
public void Money_default_should_serialize()
{
    var expected = new Money();
    var json = JsonConvert.SerializeObject(expected);
    var actual = JsonConvert.DeserializeObject<Money>(json); // Fails here
    actual.Should().NotBeNull();
    actual.Currency.Should().Be(expected.Currency);
    actual.Amount.Should().Be(expected.Amount);
}
```

**Comment by remyvd** [comment]
Merged your pull request. Thanks!

**Comment by alberthoekstra** [comment]
This has never been pushed to a new release. Is it possible you can do that?

**Comment by remyvd** [comment]
Sorry for this. Had a lot of private things going on ;-). I think it is possible. I will try to push end of december.

**Comment by alberthoekstra** [comment]
That would be awesome, thanks in advance

**Comment by wibevanklaveren** [comment]
Till now i did not see this fix. It would be awesome if this can be fixt.
