### ISSUE TITLE
Serializing default Money property in a class (PR#70)

### ISSUE THREAD

**Issue by ptjhuang** [remyvd/NodaMoney#72]
Some issue with serializing defaults in this PR.  

Nice Newtonsoft dependency is removed.  But worth mentioning if just doing a drop-in update, this is a breaking change for users who rely on JsonSerializerSetting to fine tune JSON output.  For example CamelCasePropertyContractResolver. It'll no longer have effect on Amount and Currency properties.

```
[Fact]
public void DefaultMoney_should_roundtrip()
{
    var expected = new MyClass { Value = default };
    // var expected = new MyClass { Value = new Money(0, "USD") }; // This works

    var serializer = new DataContractSerializer(typeof(MyClass));
    using (var ms = new MemoryStream()) {
        serializer.WriteObject(ms, expected);
        ms.Position = 0;

        var clone = serializer.ReadObject(ms); // throws Currency code can't be null error
        expected.Value.Should().Be(0);
    }
}

[DataContract]
private class MyClass
{
    [DataMember]
    public Money Value { get; set; }
}
```

**Comment by remyvd** [comment]
Nice catch about CamelCase not working. Don't think this can be fixed with the way how it is solved :-(. It's either this or the Newtonsoft dependcy back again...

**Comment by ptjhuang** [comment]
That's fair enough - can't exactly have one set of code that'll work around all the quirks of all serializers. 

So is your position that if anyone who wants to use Json.NET will have to provide their own MoneyJsonConverter to deal with default(Money) and default(Currency) serialization?  If that's the decision, I'm fine with that.  Although the inclusion of MoneySerializableSpec in the unit test suite kinda led me to believe it'll just work out of the box.

**Comment by ptjhuang** [comment]
@remyvd - we're running into this issue again and have been using our own fork for a while. Would you mind giving a response to this issue please?  It surrounds the following usage which in my opinion should work, and I think many others would assume so too.

Similar code fails in both: GivenIWantToSerializeMoneyWithDataContractSerializer and GivenIWantToSerializeMoneyWithJsonNetSerializer

```
[Fact]
public void WhenSerializingDefaultMoneyInComplexType_ThenThisShouldSucceed()
{
    var expected = new MyClass { Value = default, NullableValue = default };
    var actual = Clone<MyClass>(expected);
    actual.Value.Should().Be(expected.Value);
    actual.NullableValue.Should().Be(expected.NullableValue);
}

[DataContract]
private class MyClass
{
    [DataMember]
    public Money Value { get; set; }

    [DataMember]
    public Money? NullableValue { get; set; }
}
```

**Comment by remyvd** [comment]
I don't fully understand why default is important for a currency and when you would use this, because money without a proper currency goes against the idea of this library. Especially _Money?_: why don't set it to null?

In mine opinion it isn't a problem with serialization, but what the definition is of a default currency: what does it represent? I think two definition could fill the bill:
1. The currency of the current region/culture;
2. The "No Currency" in ISO-4127 (XXX, 999);

At the moment I choose "No Currency" as the best fit, because it is then fixed. What do you think about that? I succeeded into getting this working with a struct as a prototype.

**Comment by ptjhuang** [comment]
Agreed. But similar to #69, should an attempt to serialize default(Money) throw an InvalidCurrencyException, rather than whatever exception the serialization library throws?

**Comment by ptjhuang** [comment]
We did a rather large refactoring exercise to suit this behaviour.  As the library's style of treating default(Money) as almost like 'null' where doing anything operation to it is invalid.  More verbose code but admittedly less error prone.

**Comment by remyvd** [comment]
I understand te more verbose code, but this lib is about protecting you and being expliciet in defining what you mean. I think it is te safest way to move forward.

Thank you for your input, because it triggered the thinking about the definition of what default (not specified) currency is.
